In [1]:
import glob
import numpy as np
import matplotlib.pyplot as plt

from rnn import RampLSTM, generate_data

Using TensorFlow backend.


In [2]:
hit_files = glob.glob('hits_*.csv')
batch = 256
epoch_size = 448000/batch
epochs = 10

In [3]:
gen = generate_data(batch_size=batch, hit_files=hit_files)
model = RampLSTM(1000, 100, batch=batch)

In [4]:
model.train(gen, epoch_size, epochs)
model.model.save("rnn.h5")

Epoch 1/10
1750/1750 [==============================] - 1351s - loss: 0.2401  
Epoch 2/10
1750/1750 [==============================] - 1336s - loss: 0.1249  
Epoch 3/10
1750/1750 [==============================] - 1336s - loss: 0.1230  
Epoch 4/10
1750/1750 [==============================] - 1331s - loss: 0.1165  
Epoch 5/10
1750/1750 [==============================] - 1329s - loss: 0.1006  
Epoch 6/10
1750/1750 [==============================] - 1328s - loss: 0.0831  
Epoch 7/10
1750/1750 [==============================] - 1328s - loss: 0.0717  
Epoch 8/10
1750/1750 [==============================] - 1330s - loss: 0.0656  
Epoch 9/10
1750/1750 [==============================] - 1330s - loss: 0.0584  
Epoch 10/10
1750/1750 [==============================] - 1329s - loss: 0.0547  


In [5]:
model.train(gen, epoch_size, epochs)

Epoch 1/10
1750/1750 [==============================] - 1333s - loss: 0.0522  
Epoch 2/10
1750/1750 [==============================] - 1328s - loss: 0.0493  
Epoch 3/10
1750/1750 [==============================] - 1331s - loss: 0.0454  
Epoch 4/10
1750/1750 [==============================] - 1327s - loss: 0.0453  
Epoch 5/10
1750/1750 [==============================] - 1328s - loss: 0.0422  
Epoch 6/10
1750/1750 [==============================] - 1329s - loss: 0.0385  
Epoch 7/10
1750/1750 [==============================] - 1328s - loss: 0.0381  
Epoch 8/10
1750/1750 [==============================] - 1330s - loss: 0.0716  
Epoch 9/10
1750/1750 [==============================] - 1326s - loss: 0.1054  
Epoch 10/10
1750/1750 [==============================] - 1328s - loss: 0.0412  


In [17]:
ins, tars, weis = gen.next()
print tars[0]
print model.model.predict(ins)[0]

[[ 0.45287338]
 [ 0.45451848]
 [ 0.45777599]
 [ 0.46120345]
 [ 0.4654187 ]
 [ 0.4702489 ]]
[[ 0.43705845]
 [ 0.448937  ]
 [ 0.44883698]
 [ 0.4488396 ]
 [ 0.4611344 ]
 [ 0.47141308]]


In [19]:
ins, tars, weis = gen.next()
print tars[0]
print model.model.predict(ins)[0]

[[ 5.75261278]
 [ 5.75191436]
 [ 5.74997752]
 [ 5.74751671]
 [ 5.74440722]
 [ 5.74068658]]
[[ 5.66509819]
 [ 5.68485308]
 [ 5.68600607]
 [ 5.69096899]
 [ 5.7040019 ]
 [ 5.69325018]]
